Fixed a syntax error and a fatal error due to mistyping the method
The line was causing that to happen:

Fatal error: Call to undefined method Phalcon\Http\Response::setResponseCode() in /storage/htdocs/sites/phalconphp/app/controllers/IndexController.php on line 15

(see http://phalconphp.com/en/qqqqqq while the error is not fixed yet)